import type { ArchitectureModel, ApiEndpoint } from "../models/index.js";

export interface OpenApiSpec {
  openapi: string;
  info: { title: string; version: string; description: string };
  paths: Record<string, Record<string, { summary: string; operationId: string; parameters?: Array<{ name: string; in: string; schema: { type: string } }>; responses: Record<string, { description: string }> }>>;
}

/**
 * Generates OpenAPI 3.0 spec from detected API endpoints.
 */
export class ApiDocGenerator {
  constructor(private model: ArchitectureModel) {}

  generateOpenApi(): OpenApiSpec {
    const paths: OpenApiSpec["paths"] = {};

    for (const ep of this.model.apiEndpoints) {
      const path = ep.path.startsWith("/") ? ep.path : `/${ep.path}`;
      if (!paths[path]) paths[path] = {};

      const method = ep.method.toLowerCase();
      const handlerSym = this.model.symbols.get(ep.handler);
      const handlerName = handlerSym?.name?.split(".").pop() || ep.handler;

      // Extract path params
      const pathParams = path.match(/\{(\w+)\}/g)?.map((p) => p.replace(/[{}]/g, "")) || [];

      paths[path][method] = {
        summary: handlerName,
        operationId: `${method}_${path.replace(/[^a-zA-Z0-9]/g, "_")}`,
        ...(pathParams.length > 0 ? {
          parameters: pathParams.map((p) => ({ name: p, in: "path", schema: { type: "string" } })),
        } : {}),
        responses: {
          "200": { description: "Success" },
          ...(method === "post" || method === "put" ? { "400": { description: "Bad Request" } } : {}),
          "404": { description: "Not Found" },
        },
      };

      // Add query params from handler
      if (handlerSym?.params) {
        const queryParams = handlerSym.params.filter((p) => !pathParams.includes(p.name) && !["request", "req", "context", "ctx", "self", "cls"].includes(p.name));
        if (queryParams.length > 0 && !paths[path][method].parameters) {
          paths[path][method].parameters = [];
        }
        for (const qp of queryParams) {
          paths[path][method].parameters?.push({ name: qp.name, in: "query", schema: { type: qp.type || "string" } });
        }
      }
    }

    return {
      openapi: "3.0.0",
      info: {
        title: this.model.project.name,
        version: this.model.project.version,
        description: `API documentation auto-generated by ArchLens from ${this.model.apiEndpoints.length} endpoints`,
      },
      paths,
    };
  }

  generateMarkdown(): string {
    const spec = this.generateOpenApi();
    const lines: string[] = [];

    lines.push(`# ${spec.info.title} — API Documentation\n`);
    lines.push(`> ${spec.info.description}\n`);

    // Group by prefix
    const groups = new Map<string, string[]>();
    for (const path of Object.keys(spec.paths)) {
      const prefix = "/" + path.split("/").filter(Boolean).slice(0, 2).join("/");
      if (!groups.has(prefix)) groups.set(prefix, []);
      groups.get(prefix)!.push(path);
    }

    for (const [prefix, paths] of groups) {
      lines.push(`## ${prefix}\n`);
      for (const path of paths) {
        for (const [method, op] of Object.entries(spec.paths[path])) {
          lines.push(`### \`${method.toUpperCase()} ${path}\`\n`);
          lines.push(`**${op.summary}**\n`);
          if (op.parameters?.length) {
            lines.push("| Parameter | In | Type |");
            lines.push("| --- | --- | --- |");
            for (const p of op.parameters) {
              lines.push(`| ${p.name} | ${p.in} | ${p.schema.type} |`);
            }
            lines.push("");
          }
          lines.push(`**Responses:** ${Object.keys(op.responses).join(", ")}\n`);
        }
      }
    }

    lines.push("---\n*Generated by ArchLens*");
    return lines.join("\n");
  }
}
