import type { ArchitectureModel, LayerType } from "../models/index.js";
import { MermaidGenerator } from "./mermaid-generator.js";

/**
 * Generates a full Markdown architecture document.
 */
export class MarkdownGenerator {
  private mermaid: MermaidGenerator;

  constructor(private model: ArchitectureModel) {
    this.mermaid = new MermaidGenerator(model);
  }

  generate(): string {
    const sections: string[] = [];

    sections.push(this.header());
    sections.push(this.overview());
    sections.push(this.systemArchitecture());
    sections.push(this.modules());
    sections.push(this.erDiagram());
    sections.push(this.apiMap());
    sections.push(this.dataFlows());
    sections.push(this.techStack());
    sections.push(this.statistics());

    return sections.join("\n\n---\n\n");
  }

  private header(): string {
    return [
      `# ${this.model.project.name} — Architecture Document`,
      "",
      `> Generated by **ArchLens** on ${new Date(this.model.project.analyzedAt).toLocaleDateString()}`,
      "",
      "## Table of Contents",
      "1. [Overview](#overview)",
      "2. [System Architecture](#system-architecture)",
      "3. [Modules](#modules)",
      "4. [Database Schema](#database-schema)",
      "5. [API Map](#api-map)",
      "6. [Data Flows](#data-flows)",
      "7. [Tech Stack](#tech-stack)",
      "8. [Statistics](#statistics)",
    ].join("\n");
  }

  private overview(): string {
    const { stats, project } = this.model;
    const langs = Object.entries(stats.languages)
      .sort((a, b) => b[1] - a[1])
      .map(([lang, count]) => `**${lang}** (${count} symbols)`)
      .join(", ");

    return [
      "## Overview",
      "",
      `**${project.name}** is a ${this.model.modules.length}-module project with ${stats.files} files and ${stats.totalLines.toLocaleString()} lines of code.`,
      "",
      `**Languages:** ${langs}`,
      "",
      `| Metric | Count |`,
      `| --- | --- |`,
      `| Files | ${stats.files} |`,
      `| Symbols | ${stats.symbols} |`,
      `| Relations | ${stats.relations} |`,
      `| Modules | ${stats.modules} |`,
      `| Lines of Code | ${stats.totalLines.toLocaleString()} |`,
    ].join("\n");
  }

  private systemArchitecture(): string {
    return [
      "## System Architecture",
      "",
      "```mermaid",
      this.mermaid.generateC4Architecture(),
      "```",
    ].join("\n");
  }

  private modules(): string {
    const lines = ["## Modules", ""];

    const layerOrder: LayerType[] = [
      "presentation", "api", "application", "domain", "infrastructure", "config",
    ];

    for (const layer of layerOrder) {
      const mods = this.model.modules.filter((m) => m.layer === layer);
      if (mods.length === 0) continue;

      lines.push(`### ${layer.charAt(0).toUpperCase() + layer.slice(1)} Layer`);
      lines.push("");

      for (const mod of mods) {
        lines.push(`#### \`${mod.name}/\``);
        lines.push(`- **Language:** ${mod.language}`);
        lines.push(`- **Files:** ${mod.fileCount}`);
        lines.push(`- **Lines:** ${mod.lineCount.toLocaleString()}`);
        lines.push(`- **Symbols:** ${mod.symbols.length}`);
        lines.push("");
      }
    }

    return lines.join("\n");
  }

  private erDiagram(): string {
    return [
      "## Database Schema",
      "",
      "```mermaid",
      this.mermaid.generateERDiagram(),
      "```",
      "",
      this.model.dbEntities.length > 0
        ? `**${this.model.dbEntities.length} entities** detected with ${this.model.dbEntities.reduce((a, e) => a + e.columns.length, 0)} columns total.`
        : "_No database entities detected. Add SQLAlchemy/Prisma/TypeORM models to auto-detect._",
    ].join("\n");
  }

  private apiMap(): string {
    const lines = [
      "## API Map",
      "",
      "```mermaid",
      this.mermaid.generateAPIMap(),
      "```",
    ];

    if (this.model.apiEndpoints.length > 0) {
      lines.push("");
      lines.push("| Method | Path | Handler |");
      lines.push("| --- | --- | --- |");
      for (const ep of this.model.apiEndpoints) {
        lines.push(`| \`${ep.method}\` | \`${ep.path}\` | \`${ep.handler}\` |`);
      }
    }

    return lines.join("\n");
  }

  private dataFlows(): string {
    const lines = [
      "## Data Flows",
      "",
      "```mermaid",
      this.mermaid.generateDataFlow(),
      "```",
    ];

    for (const flow of this.model.dataFlows) {
      lines.push("");
      lines.push(`### ${flow.name}`);
      if (flow.description) lines.push(`> ${flow.description}`);
      lines.push("");
      for (const step of flow.steps) {
        lines.push(`${step.order}. **${step.source}** → \`${step.action}\` → **${step.target}**`);
      }
    }

    return lines.join("\n");
  }

  private techStack(): string {
    const lines = [
      "## Tech Stack",
      "",
      "```mermaid",
      this.mermaid.generateTechRadar(),
      "```",
      "",
      "| Name | Version | Category | Source |",
      "| --- | --- | --- | --- |",
    ];

    for (const entry of this.model.techRadar) {
      lines.push(`| ${entry.name} | ${entry.version || "-"} | ${entry.category} | ${entry.source} |`);
    }

    return lines.join("\n");
  }

  private statistics(): string {
    return [
      "## Statistics",
      "",
      "```mermaid",
      this.mermaid.generateDependencyGraph(),
      "```",
    ].join("\n");
  }
}
