import type { QualityReport, ModuleQuality, PatternAnalysis } from "../analyzers/quality-analyzer.js";

/**
 * Generates quality report in Markdown format
 */
export class QualityReportGenerator {
  constructor(private report: QualityReport) {}

  toMarkdown(): string {
    const r = this.report;
    const lines: string[] = [];

    lines.push(`# Code Quality Report — Score: ${r.projectScore}/100\n`);
    lines.push(`> Generated by ArchLens\n`);

    // Summary
    lines.push("## Summary\n");
    lines.push(`| Metric | Value |`);
    lines.push(`| --- | --- |`);
    lines.push(`| Overall Score | **${r.projectScore}/100** |`);
    lines.push(`| Total Issues | ${r.totalIssues} |`);
    lines.push(`| Critical | ${r.bySeverity.critical || 0} |`);
    lines.push(`| Major | ${r.bySeverity.major || 0} |`);
    lines.push(`| Minor | ${r.bySeverity.minor || 0} |`);
    lines.push(`| Info | ${r.bySeverity.info || 0} |\n`);

    // Architecture Patterns
    lines.push("## Architecture Pattern Compliance\n");
    for (const pat of r.architecturePatterns) {
      const emoji = pat.compliance >= 80 ? "✅" : pat.compliance >= 50 ? "⚠️" : pat.compliance > 0 ? "❌" : "➖";
      lines.push(`### ${emoji} ${pat.pattern} — ${pat.compliance}%\n`);
      lines.push(`**Status:** ${pat.detected ? "Detected" : "Not detected"}\n`);
      if (pat.violations.length > 0) {
        lines.push("**Violations:**");
        for (const v of pat.violations) lines.push(`- ❌ ${v}`);
        lines.push("");
      }
      if (pat.recommendations.length > 0) {
        lines.push("**Recommendations:**");
        for (const r of pat.recommendations) lines.push(`- 💡 ${r}`);
        lines.push("");
      }
    }

    // Module Scores
    lines.push("## Module Quality Scores\n");
    lines.push("| Module | Score | Issues | God Classes | Naming | Type Safety |");
    lines.push("| --- | --- | --- | --- | --- | --- |");
    for (const mod of [...r.modules].sort((a, b) => a.score - b.score)) {
      lines.push(`| ${mod.moduleName} | **${mod.score}**/100 | ${mod.issues.length} | ${mod.metrics.godClasses} | ${mod.metrics.namingViolations} | ${mod.metrics.typeUnsafe} |`);
    }
    lines.push("");

    // Top Issues
    lines.push("## Top Issues\n");
    for (const issue of r.topIssues.slice(0, 20)) {
      const icon = issue.severity === "critical" ? "🔴" : issue.severity === "major" ? "🟠" : issue.severity === "minor" ? "🟡" : "🔵";
      lines.push(`${icon} **${issue.rule}**: ${issue.message}`);
      if (issue.filePath) lines.push(`   📄 ${issue.filePath}${issue.line ? `:${issue.line}` : ""}`);
      if (issue.suggestion) lines.push(`   💡 ${issue.suggestion}`);
      lines.push("");
    }

    lines.push("---");
    lines.push("*Generated by [ArchLens](https://github.com/muhsinelcicek/archlens)*");

    return lines.join("\n");
  }

  toJSON(): string {
    return JSON.stringify(this.report, null, 2);
  }
}
