export { ProjectScanner } from "./project-scanner.js";
export type { ScanOptions } from "./project-scanner.js";
export { ProcessDetector } from "./process-detector.js";
export type { BusinessProcess, DataSource, ProcessStep, ProcessOutput } from "./process-detector.js";
export { ModuleResolver } from "./module-resolver.js";
export { GitDiffer } from "./git-differ.js";
export { IncrementalCache } from "./incremental-cache.js";
export { SequenceTracer } from "./sequence-tracer.js";
export { QualityAnalyzer } from "./quality-analyzer.js";
export type { QualityReport, QualityIssue, ModuleQuality, PatternAnalysis, Severity, IssueCategory } from "./quality-analyzer.js";
export { DeadCodeDetector } from "./dead-code-detector.js";
export type { DeadCodeReport, DeadCodeItem } from "./dead-code-detector.js";
export { SecurityScanner } from "./security-scanner.js";
export type { SecurityReport, SecurityIssue } from "./security-scanner.js";
export { HotspotAnalyzer } from "./hotspot-analyzer.js";
export type { HotspotReport, Hotspot } from "./hotspot-analyzer.js";
export { DuplicateDetector } from "./duplicate-detector.js";
export type { DuplicateReport, DuplicateGroup } from "./duplicate-detector.js";
export { RefactoringSuggester } from "./refactoring-suggester.js";
export type { RefactoringReport, RefactoringSuggestion } from "./refactoring-suggester.js";
export { DiffAnalyzer } from "./diff-analyzer.js";
export type { ArchDiff } from "./diff-analyzer.js";
export { CustomRuleEngine } from "./custom-rules.js";
export type { CustomRule, CustomRulesReport, RuleViolation } from "./custom-rules.js";
export { VulnerabilityChecker } from "./vulnerability-checker.js";
export type { VulnerabilityReport, VulnerableDependency } from "./vulnerability-checker.js";
export { TechDebtCalculator } from "./tech-debt-calculator.js";
export type { TechDebtReport, DebtItem } from "./tech-debt-calculator.js";
export { EventFlowDetector } from "./event-flow-detector.js";
export type { EventFlowReport, EventFlow, BoundedContext } from "./event-flow-detector.js";
export { PatternDeepAnalyzer } from "./pattern-deep-analyzer.js";
export type { DeepPatternAnalysis, PatternEvidence } from "./pattern-deep-analyzer.js";
export { calculateComplexity, getLanguageRules } from "./language-rules.js";
export type { SequenceDiagram, SequenceStep } from "./sequence-tracer.js";
export type { DriftReport, ChangedFile, SymbolChange, DependencyChange, LayerViolation } from "./git-differ.js";
